### ISSUE TITLE
SGD + Momentum Implementation

### ISSUE THREAD

**Issue by getaleks** [NLeSC/deep-learning-assignments-solutions#2]
Hi,

can you explain why SGD+Momentum is implemented like this:

`  v = mu * v - learning_rate * dw`
`next_w = w + v`

In lecture 7, slide 21 it says the formula is:
`dx = compute_gradient(x)`
`vx = rho * vx + dx`
`x += learning_rate * vx`

**Comment by vincentvanhees** [comment]
It would help if you could add a link to the current course slides and a link to that part of our code, because we have not looked at this for a while.

We did this with a group and not all of us really tried to do all the assignments, so wrong assignments are to be expected in this repo. Further, we used lecture slides from last year, which may explain the different name convention.

**Comment by getaleks** [comment]
Hi Vincent,

Thanks for the reply.

You can find the slides here:
http://cs231n.stanford.edu/slides/2017/cs231n_2017_lecture7.pdf
Scroll down to slide 21 and you'll see the formula.

And here is a link to the code in question:
https://github.com/NLeSC/deep-learning-assignments-solutions/blob/9a8f4612da0be6123cd1660254233f2cda6e1c6d/assignment2/berend/cs231n/optim.py#L71


The above link is from Berend's solution, however you seem to have implemented SGD+Momentum the same way:
https://github.com/NLeSC/deep-learning-assignments-solutions/blob/9a8f4612da0be6123cd1660254233f2cda6e1c6d/assignment2/vincent/cs231n/optim.py#L70

**Comment by vincentvanhees** [comment]
Our answer is similar to what was in the 2015/2016 slides: http://cs231n.stanford.edu/slides/2016/winter1516_lecture6.pdf
So, it seems like the course organizers updated the SGD+momentum calculation.

**Comment by getaleks** [comment]
Ok, well that explains it.
It's probably the same thing then, only written differently. 

Thanks for the clarification.
